# Site settings

title: antonia
description: If you love your business as much as I love my job, we're off to a good start!

email: antoniyaat@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://antoniyaat.github.io" 

github_username: antoniyaat

future: true
markdown: kramdown

plugins:
- jekyll-feed
- jekyll-paginate

destination: docs

exclude:
- Gemfile
- Gemfile.lock
- package.json
- gulpfile.js
- docs
- node_modules
- scss

paginate: 6
paginate_path: "/blog/page:num/"